services:
  - type: web
    name: complaint-chatbot-backend
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn run:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PORT
        value: 10000
